os: Visual Studio 2015

platform: x64

environment:
        matrix:
        - test_moar: 2016.11
        - test_moar: '' #latest

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl --allow-empty-checksums
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/tadzik/rakudobrew %USERPROFILE%\rakudobrew
  - SET PATH=%USERPROFILE%\rakudobrew\bin;%PATH%
  - rakudobrew build moar %TEST_MOAR%
  - rakudobrew build zef
  - cd %APPVEYOR_BUILD_FOLDER%
  - zef --depsonly install .
  - zef install Test::META
  - zef build .

build: off

test_script:
  - set AUTHOR_TESTING=1 && prove -ve "perl6 -Ilib"
  - zef --debug install .

shallow_clone: true
